### ISSUE TITLE
Exception when using multiple R scripts inside a Task

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/connector-r#85]
```
[399t0@xstoocky09.mgps.inra.fr;17:04:47] 2016-06-24 17:04:47.0036 ERROR main org.ow2.parengine.PAREngine - Unable to instantiate the PAJRIEngine 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] An exception occurred while executing the script FlowScript, and content: 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] org.rosuda.REngine.REngineException: engine already running - cannot use extended constructor on a running instance 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.rosuda.REngine.JRI.JRIEngine.createEngine(JRIEngine.java:113) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] runs <- 2 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.pajri.PAJRIEngine.createScriptEngine(PAJRIEngine.java:77) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.pajri.PAJRIEngine.create(PAJRIEngine.java:55) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.pajri.PAJRIFactory.getScriptEngine(PAJRIFactory.java:22) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scripting.Script.createScriptEngine(Script.java:366) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scripting.Script.execute(Script.java:285) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.executeFlowScript(InProcessTaskExecutor.java:226) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:154) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] 2016-06-24 17:04:47.0048 ERROR main org.ow2.proactive.scheduler.task.TaskResultImpl - 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] java.io.NotSerializableException: org.rosuda.REngine.JRI.JRIEngine 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.lang.Throwable.writeObject(Throwable.java:985) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.lang.reflect.Method.invoke(Method.java:606) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.lang.Throwable.writeObject(Throwable.java:985) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.lang.reflect.Method.invoke(Method.java:606) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.lang.Throwable.writeObject(Throwable.java:985) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.lang.reflect.Method.invoke(Method.java:606) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.writeToStream(ObjectToByteConverter.java:92) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.standardConvert(ObjectToByteConverter.java:110) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.convert(ObjectToByteConverter.java:88) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.access$000(ObjectToByteConverter.java:51) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter$ObjectStream.convert(ObjectToByteConverter.java:83) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.TaskResultImpl.computeSerializedException(TaskResultImpl.java:179) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.TaskResultImpl.setException(TaskResultImpl.java:234) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.executeFlowScript(InProcessTaskExecutor.java:230) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:154) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[399t0@xstoocky09.mgps.inra.fr;17:04:47] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78)
```

**Comment by fviale** [comment]
The error occurs as well if we use a pre and a task script:
```
[1325t0@138.102.172.119;10:42:34] 2016-07-01 10:42:34.0852 ERROR main org.ow2.parengine.PAREngine - Unable to instantiate the PAJRIEngine 
[1325t0@138.102.172.119;10:42:34] Failed to execute task: An exception occurred while executing the script TaskScript with parameters=[], and content: 
[1325t0@138.102.172.119;10:42:34] org.rosuda.REngine.REngineException: engine already running - cannot use extended constructor on a running instance 
[1325t0@138.102.172.119;10:42:34] 
[1325t0@138.102.172.119;10:42:34] cat('Hello, world!\n') 
[1325t0@138.102.172.119;10:42:34] at org.rosuda.REngine.JRI.JRIEngine.createEngine(JRIEngine.java:113) 
[1325t0@138.102.172.119;10:42:34] 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIEngine.createScriptEngine(PAJRIEngine.java:77) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:202) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIEngine.create(PAJRIEngine.java:55) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:141) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIFactory.getScriptEngine(PAJRIFactory.java:22) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.Script.createScriptEngine(Script.java:366) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.Script.execute(Script.java:285) 
[1325t0@138.102.172.119;10:42:34] Caused by: org.ow2.proactive.scripting.ScriptException: An exception occurred while executing the script TaskScript with parameters=[], and content: 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[1325t0@138.102.172.119;10:42:34] 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:198) 
[1325t0@138.102.172.119;10:42:34] cat('Hello, world!\n') 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:141) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[1325t0@138.102.172.119;10:42:34] 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:81) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:198) 
[1325t0@138.102.172.119;10:42:34] ... 3 more 
[1325t0@138.102.172.119;10:42:34] Caused by: java.lang.RuntimeException: Unable to create the PAJRIEngine 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIFactory.getScriptEngine(PAJRIFactory.java:24) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.Script.createScriptEngine(Script.java:366) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.Script.execute(Script.java:285) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[1325t0@138.102.172.119;10:42:34] ... 4 more 
[1325t0@138.102.172.119;10:42:34] Caused by: java.lang.IllegalStateException: Unable to instantiate the PAJRIEngine 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIEngine.createScriptEngine(PAJRIEngine.java:80) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIEngine.create(PAJRIEngine.java:55) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIFactory.getScriptEngine(PAJRIFactory.java:22) 
[1325t0@138.102.172.119;10:42:34] ... 7 more 
[1325t0@138.102.172.119;10:42:34] Caused by: org.rosuda.REngine.REngineException: engine already running - cannot use extended constructor on a running instance 
[1325t0@138.102.172.119;10:42:34] at org.rosuda.REngine.JRI.JRIEngine.createEngine(JRIEngine.java:113) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.pajri.PAJRIEngine.createScriptEngine(PAJRIEngine.java:77) 
[1325t0@138.102.172.119;10:42:34] ... 9 more 
[1325t0@138.102.172.119;10:42:34] 2016-07-01 10:42:34.0871 ERROR main org.ow2.proactive.scheduler.task.TaskResultImpl - 
[1325t0@138.102.172.119;10:42:34] java.io.NotSerializableException: org.rosuda.REngine.JRI.JRIEngine 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[1325t0@138.102.172.119;10:42:34] at java.lang.Throwable.writeObject(Throwable.java:985) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[1325t0@138.102.172.119;10:42:34] at java.lang.reflect.Method.invoke(Method.java:606) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[1325t0@138.102.172.119;10:42:34] at java.lang.Throwable.writeObject(Throwable.java:985) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[1325t0@138.102.172.119;10:42:34] at java.lang.reflect.Method.invoke(Method.java:606) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[1325t0@138.102.172.119;10:42:34] at java.lang.Throwable.writeObject(Throwable.java:985) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[1325t0@138.102.172.119;10:42:34] at java.lang.reflect.Method.invoke(Method.java:606) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:440) 
[1325t0@138.102.172.119;10:42:34] at java.lang.Throwable.writeObject(Throwable.java:985) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
[1325t0@138.102.172.119;10:42:34] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[1325t0@138.102.172.119;10:42:34] at java.lang.reflect.Method.invoke(Method.java:606) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) 
[1325t0@138.102.172.119;10:42:34] at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347) 
[1325t0@138.102.172.119;10:42:34] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.writeToStream(ObjectToByteConverter.java:92) 
[1325t0@138.102.172.119;10:42:34] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.standardConvert(ObjectToByteConverter.java:110) 
[1325t0@138.102.172.119;10:42:34] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.convert(ObjectToByteConverter.java:88) 
[1325t0@138.102.172.119;10:42:34] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter.access$000(ObjectToByteConverter.java:51) 
[1325t0@138.102.172.119;10:42:34] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter$ObjectStream.convert(ObjectToByteConverter.java:83) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.TaskResultImpl.computeSerializedException(TaskResultImpl.java:179) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.TaskResultImpl.<init>(TaskResultImpl.java:172) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:151) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[1325t0@138.102.172.119;10:42:34] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
```

**Comment by fviale** [comment]
related to fix for issue https://github.com/ow2-proactive/connector-r/issues/70

The script engine is closed at each script evaluation, and we are not able to reopen it
